export const categories = [
  { id: 1, name: "PC방" },
  { id: 2, name: "산책" },
  { id: 3, name: "카페" },
  { id: 4, name: "반려동물" },
  { id: 5, name: "드라마" },
  { id: 6, name: "맛집" },
  { id: 7, name: "전시회" },
  { id: 8, name: "만화" },
  { id: 9, name: "방탈출" },
  { id: 10, name: "캠핑" },
  { id: 11, name: "쇼핑" },
  { id: 12, name: "스포츠" },
  { id: 13, name: "인스타그램" },
  { id: 14, name: "언어교환" },
  { id: 15, name: "영화" },
  { id: 16, name: "독서" },
  { id: 17, name: "노래방" },
  { id: 18, name: "요리" },
  { id: 19, name: "술" },
  { id: 20, name: "패션" },
  { id: 21, name: "여행" },
  { id: 22, name: "등산" },
  { id: 23, name: "사진" },
  { id: 24, name: "봉사" },
];
